services:
  api:
    build: .
    container_name: rentnearby_api
    restart: unless-stopped
    environment:
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION_STRING}
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: RentNearBy
      Jwt__Audience: RentNearBy
      REDIS_URL: ${REDIS_URL}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    ports:
      - "5000:5000"
